/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/*
 * NOTICE
 * 
 * This software (or technical data) was produced for the U. S. Government and
 * is subject to the Rights in Data-General Clause 52.227-14,
 * Alt. IV (May 2014) – Alternative IV (Dec 2007)
 *
 * © 2023 The MITRE Corporation.
 */
package org.mitre.tlshmodule;

import java.util.logging.Level;
import javax.swing.JOptionPane;
import org.sleuthkit.autopsy.coreutils.Logger;
import org.sleuthkit.autopsy.coreutils.ModuleSettings;


public class CreateTlshHashSetDialog extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(CreateTlshHashSetDialog.class.getName());

    private boolean isCreating = false;

    /**
     * Creates new form CreateTlshHashSetDialog
     */
    public CreateTlshHashSetDialog(java.awt.Frame parent, boolean modal, boolean isCreating, String settingName) {
        super(parent, modal);
        initComponents();
        this.isCreating = isCreating;

        // if it is not creating a new hash set, then do not allow the name to be modified
        this.hashSetNameTextField.setEditable(isCreating);

        // if it is in edit mode (isCreating == false) then populate the fields
        if (!isCreating) {
            this.hashSetNameTextField.setText(settingName);
            this.hashSetTextArea.setText(ModuleSettings.getConfigSetting(
                    TlshIngestModuleFactory.getModuleName(), settingName));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hashSetNameLabel = new javax.swing.JLabel();
        hashSetNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hashSetTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(hashSetNameLabel, org.openide.util.NbBundle.getMessage(CreateTlshHashSetDialog.class, "CreateTlshHashSetDialog.hashSetNameLabel.text_1")); // NOI18N

        hashSetNameTextField.setText(org.openide.util.NbBundle.getMessage(CreateTlshHashSetDialog.class, "CreateTlshHashSetDialog.hashSetNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateTlshHashSetDialog.class, "CreateTlshHashSetDialog.jLabel1.text_1")); // NOI18N

        hashSetTextArea.setColumns(20);
        hashSetTextArea.setRows(5);
        jScrollPane1.setViewportView(hashSetTextArea);

        org.openide.awt.Mnemonics.setLocalizedText(saveButton, org.openide.util.NbBundle.getMessage(CreateTlshHashSetDialog.class, "CreateTlshHashSetDialog.saveButton.text")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(CreateTlshHashSetDialog.class, "CreateTlshHashSetDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hashSetNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hashSetNameLabel)
                                .addGap(0, 286, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hashSetNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hashSetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Saves the hash set that the user inputted into the text area along with the name they gave the hash set.
     * 
     * @param evt Event from clicking the button.
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // if the setting exists and user is trying to create a new one, do not allow this
        if (ModuleSettings.settingExists(TlshIngestModuleFactory.getModuleName(), hashSetNameTextField.getText())
                && this.isCreating) {
            logger.log(Level.INFO, "Name for the hashset {0} already exists", hashSetNameTextField.getText());
            JOptionPane.showMessageDialog(this, "Name for this hash set already exists.");
            return;
        }

        String inputedHashes = hashSetTextArea.getText();

        if (!inputedHashes.isEmpty()) {
            ModuleSettings.setConfigSetting(TlshIngestModuleFactory.getModuleName(),
                    hashSetNameTextField.getText(), inputedHashes);

            // Clear the fields
            this.setVisible(false);

            hashSetNameTextField.setText("");
            hashSetTextArea.setText("");
        } else {
            // Throw error message
            logger.log(Level.INFO, "Nothing was inputted in the text field.");
            JOptionPane.showMessageDialog(this, "There was no text inputted.");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * Removes any text that the user typed in the field and close the window.
     * 
     * @param evt Event that the user clicked the cancel button.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
        hashSetNameTextField.setText("");
        hashSetTextArea.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel hashSetNameLabel;
    private javax.swing.JTextField hashSetNameTextField;
    private javax.swing.JTextArea hashSetTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
